Upgrade Google Core Library - Guava - to latest available version - 29.
Appium java-client 7.3.0 has a transitive dependency for version 25 that doesn't have a support for collections streaming.
ChromeOptions is a newer class that uses the .asMap() streaming method and needs it, otherwise NoSuchMethodError is thrown in runtime.

Signed-off-by: Marat Strelets <marat@testproject.io>